name: recycle_guide
description: 분리수거 가이드 — 뭘 어디에 버릴까?
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0        # AdMob
  shared_preferences: ^2.3.2       # 최근 검색어 저장
  share_plus: ^10.0.0              # 공유 기능

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
